import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { Providers } from "./providers";
import './globals.css'

const inter = Ubuntu({ subsets: ["cyrillic"], weight: '700' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#fafafa]">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
